image: kaiwinter/docker-java8-maven

stages:
  - release

upload-jar-to-nexus:
  stage: release
  variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  script:
    - MVN_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
    - if [[ $MVN_VERSION != $CI_COMMIT_TAG ]]; then exit 1; fi
    - mvn $MAVEN_CLI_OPTS -DskipTests clean deploy
  only:
    - tags
